name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: SantanderNycz
          outputs: snake.svg

      - name: Show generated files
        run: ls -la

      - name: Commit and push
        if: steps.snake.outputs.snake_created == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add snake.svg
          git commit -m "Update snake animation"
          git push
