name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Atualiza diariamente
  workflow_dispatch:       # Permite executar manualmente
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permite fazer push

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Importante para o Platane/snk

      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake
        with:
          github_user_name: SantanderNycz  # 👈 Seu usuário
          outputs: |
            output/snake.svg  # Salva em /output

      - name: Verify File
        run: |
          ls -la output/  # Lista arquivos gerados
          [ -f output/snake.svg ] || exit 1  # Falha se não existir

      - name: Commit & Push
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add output/snake.svg
          git commit -m "Update snake.svg"
          git push
