name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente
  workflow_dispatch:      # Permite trigger manual

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permissão ESSENCIAL

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessário para o Platane/snk

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: SantanderNycz  # 👈 Seu usuário GitHub
          outputs: snake.svg  # Gera na raiz do repositório

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add snake.svg
          git commit -m "Update snake animation"
          git push
