name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente
  workflow_dispatch:      # Permite trigger manual

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permissão ESSENCIAL

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necessário para o Platane/snk

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: SantanderNycz
          outputs: |
            snake.svg          # Versão padrão (light)
            snake-dark.svg     # Versão dark
          theme: dark          # Opcional: define o tema padrão
          # Outras opções:
          # color: orange       # Cor personalizada
          # type: gif           # Se quiser em GIF (não recomendado para README)

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add snake.svg snake-dark.svg
          git commit -m "Update snake animations"
          git push
