name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: SantanderNycz
          svg_path: ./snake.svg
          
      - name: Commit and Push
        if: steps.snake.outputs.snake_created == 'true'
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add snake.svg
          git commit -m "Update snake animation"
          git push
